# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'TukTalk-iOS' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for TukTalk-iOS

pod 'RxSwift'
pod 'RxCocoa'
pod 'SnapKit'
pod 'Moya'
pod 'Moya/RxSwift'
pod 'Then'

  target 'TukTalk-iOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'TukTalk-iOSUITests' do
    # Pods for testing
  end

end
